// Write dist/llms.txt from the pages that were actually built.
//
// WHAT IT IS FOR, HONESTLY
// Google says in as many words that llms.txt is not read by Google Search and
// changes nothing there, so this file earns nothing from the engine that sends
// most of the traffic. It is written anyway for the same reason robots.txt
// carries no Disallow: the owner's decision of 27.08.2026 is that this page
// wants to be quoted by the answer engines, and several of the smaller ones do
// fetch it. A 2KB text file is a cheap bet on that.
//
// It is NOT a place to say anything the pages do not already say. Every line
// below is read out of the built documents: the title and the description each
// page declares in its own head. A hand-written llms.txt is the hand-written
// sitemap again — right on the day it is written and wrong within the week.
//
//   node scripts/build-llms.mjs

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const DIST = path.join(ROOT, 'dist')
const ORIGIN = 'https://inplace.digital'

function pages(dir = DIST, prefix = '/') {
  const found = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (entry.name === 'assets') continue
      found.push(...pages(path.join(dir, entry.name), `${prefix}${entry.name}/`))
    } else if (entry.name === 'index.html') {
      found.push({ url: prefix, file: path.join(dir, entry.name) })
    }
  }
  return found
}

const between = (html, re) => (html.match(re) || [])[1] || ''
const decode = (s) =>
  s
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, ' ')

const all = pages().map(({ url, file }) => {
  const html = readFileSync(file, 'utf8')
  return {
    url,
    title: decode(between(html, /<title>([\s\S]*?)<\/title>/)).trim(),
    description: decode(between(html, /<meta\s+name="description"\s+content="([^"]*)"/)).trim(),
  }
})

if (!all.length) {
  console.error('no pages in dist/. Run `vite build` first.')
  process.exit(1)
}

// Two lists, because the site is one product said twice and an engine reading
// this should not have to guess which sixteen of the eighteen URLs are
// translations of the other eight.
const he = all.filter((p) => !p.url.startsWith('/en/'))
const en = all.filter((p) => p.url.startsWith('/en/'))

const missing = all.filter((p) => !p.title || !p.description)
if (missing.length) {
  console.error('llms.txt NOT written:')
  for (const p of missing) console.error(`   ${p.url} has no title or no description`)
  process.exit(1)
}

const list = (rows) =>
  rows
    .sort((a, b) => a.url.length - b.url.length || a.url.localeCompare(b.url))
    .map((p) => `- [${p.title}](${ORIGIN}${p.url}): ${p.description}`)
    .join('\n')

const text = `# InPlace

> מערכת רכש עד תשלום בעברית מלאה: כל הזמנה, קבלת סחורה וחשבונית בשרשרת אחת, עם
> בדיקה אוטומטית שעוצרת את מה שלא מתאים לפני שמשלמים. A procurement-to-payment
> system in full Hebrew and English, connecting purchase orders, goods received
> and invoices, and stopping mismatches before money leaves the business.

Generated by scripts/build-llms.mjs from the pages in the build. Do not edit by hand.

Operated by In Place, a business registered in Israel. Registration number
036689081. Contact: support@inplace.digital.

## עברית

${list(he)}

## English

${list(en)}

## Notes

- Every page above is served as complete HTML with no JavaScript required. The
  words a crawler receives are the words a reader receives.
- The customer quotes on the home page are written in-house as examples, and the
  page says so in its own words. They are not customer reviews, and no review or
  rating markup is published anywhere on this site.
- Prices are published in shekels on the Hebrew pages and in dollars on the
  English ones. They are two catalogues, not one converted at a rate.
`

writeFileSync(path.join(DIST, 'llms.txt'), text)
console.log(`dist/llms.txt  ${all.length} pages, ${(text.length / 1024).toFixed(1)}KB`)
