// Write dist/sitemap.xml from the pages that were actually built.
//
// The first cut of this was a hand-written public/sitemap.xml with one URL in
// it, and it was wrong within the hour: a second locale appeared at /en/ and
// the file did not know. A sitemap that has to be remembered is a sitemap that
// goes stale, and a stale sitemap is worse than none, because it tells a
// crawler that the pages it lists are the pages that exist.
//
// So the list is derived, not declared. Every index.html under dist/ is a page,
// every screen-*.webp under dist/assets is a product screenshot, and both of
// those are facts about the build rather than notes about it.
//
// It also refuses to write a sitemap it does not believe: if a page carries a
// canonical that points somewhere other than the page's own address, the two
// are in conflict and the sitemap would be advertising an address the page
// itself disowns. That is the exact failure a second locale invites, because
// the usual way to add one is to copy the first locale's <head>.
//
//   node scripts/build-sitemap.mjs

import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const DIST = path.join(ROOT, 'dist')
const ORIGIN = 'https://inplace.digital'

/** Every index.html in the build, as a site-absolute path with a trailing slash. */
function pages(dir = DIST, prefix = '/') {
  const found = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (entry.name === 'assets') continue
      found.push(...pages(path.join(dir, entry.name), `${prefix}${entry.name}/`))
    } else if (entry.name === 'index.html') {
      found.push({ url: prefix, file: path.join(dir, entry.name) })
    }
  }
  return found
}

const iso = (file) => statSync(file).mtime.toISOString().slice(0, 10)

const canonicalOf = (html) => {
  const m = html.match(/<link[^>]+rel=["']canonical["'][^>]*>/i)
  return m ? (m[0].match(/href=["']([^"']+)["']/i) || [])[1] || null : null
}

const found = pages().sort((a, b) => a.url.length - b.url.length || a.url.localeCompare(b.url))
if (!found.length) {
  console.error('no pages in dist/. Run `vite build` first.')
  process.exit(1)
}

// The screenshots are the one thing on this site worth surfacing in image
// search: they are the product, photographed. They hang off the root page
// because an image belongs to one page, and the root is the Hebrew original.
const shots = readdirSync(path.join(DIST, 'assets'))
  .filter((f) => /^screen-.*\.webp$/.test(f))
  .sort()

const problems = []
const entries = found.map(({ url, file }) => {
  const html = readFileSync(file, 'utf8')
  const declared = canonicalOf(html)
  const expected = `${ORIGIN}${url}`
  if (declared && declared !== expected) {
    problems.push(`${url} declares canonical ${declared}, but it is served at ${expected}`)
  }
  if (!declared) problems.push(`${url} has no canonical`)
  return { url, expected, lastmod: iso(file) }
})

if (problems.length) {
  console.error('sitemap NOT written:')
  for (const p of problems) console.error(`   ${p}`)
  process.exit(1)
}

const images = shots
  .map((f) => `      <image:image><image:loc>${ORIGIN}/assets/${f}</image:loc></image:image>`)
  .join('\n')

const body = entries
  .map(
    ({ url, expected, lastmod }) =>
      `  <url>\n` +
      `    <loc>${expected}</loc>\n` +
      `    <lastmod>${lastmod}</lastmod>\n` +
      `    <changefreq>weekly</changefreq>\n` +
      `    <priority>${url === '/' ? '1.0' : '0.8'}</priority>\n` +
      (url === '/' && images ? `${images}\n` : '') +
      `  </url>`
  )
  .join('\n')

const xml =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<!-- Generated by scripts/build-sitemap.mjs. Do not edit by hand. -->\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n` +
  `        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n` +
  `${body}\n` +
  `</urlset>\n`

writeFileSync(path.join(DIST, 'sitemap.xml'), xml)
console.log(
  `dist/sitemap.xml  ${entries.length} page${entries.length === 1 ? '' : 's'} ` +
    `(${entries.map((e) => e.url).join(', ')}), ${shots.length} images`
)
